In [1]:
import tensorflow as tf

print(tf.__version__)


2.15.0


In [7]:
# Crear un tensor
tensor = tf.constant([[23, 4, 1], [32, 51, 6]])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[23,  4,  1],
       [32, 51,  6]])>

In [8]:
# Obtener el número de dimensiones
print(tensor.ndim)

2


In [9]:
# Obtener la forma del tensor
print(tensor.shape)

(2, 3)


In [10]:
# Obtener el tipo de datos del tensor
print(tensor.dtype)

<dtype: 'int32'>


In [11]:
# Obtener el tamaño del tensor
print(tf.size(tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [13]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank_4_tensor.ndim

4

In [16]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [18]:
tensor = tf.zeros([2,3,4])
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [20]:
tensor2 = tf.zeros([])
tensor2

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>