# Creando el primer tensor

En el presente notebook se muestra cómo crear un tensor en TensorFlow 2.0

In [2]:
# importamos tensorflow
import tensorflow as tf

# veamos la versión de tensorflow que estamos trabajando
print(tf.__version__)

2.15.0


In [3]:
# Creando un tensor con tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Verificamos la dimensión del tensor
scalar.ndim

0

In [6]:
# Creando un vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
# Verificamos la dimensión del tensor
vector.ndim

1

In [9]:
# Creando una matriz
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
# Verificamos la dimensión del tensor
matrix.ndim

2

In [11]:
# Creando otra matriz
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) #  especificamos el tipo de dato
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# Verificamos la dimensión del tensor
another_matrix.ndim

2

In [14]:
# Creando un tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [15]:
# Verificamos la dimensión del tensor
tensor.ndim

3