In [1]:
import tensorflow as tf

In [3]:
# Creando un tensor de 2x2 con todos los elementos en 1
tf.ones(shape=[2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [4]:
# Creando un tensor de 2x2 con todos los elementos en 0
tf.zeros(shape=[2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

La principal diferencia entre un tensor y un array de numpy es que los tensores pueden ser ejecutados en una GPU o TPU para acelerar los cálculos.

In [5]:
import numpy as np

# Creando un array de numpy
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [6]:
# Creando un tensor desde un array de numpy
tensor_A = tf.constant(numpy_A, shape=[2, 3, 4])
tensor_A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>