Los tensores aleatorios son tensores cuyos elementos son generados aleatoriamente. En este notebook se presentan ejempador de tensores aleatorios en TensorFlow.

In [1]:
import tensorflow as tf

print(tf.__version__)


2.15.0


In [7]:
random_1 = tf.random.Generator.from_seed(1234)

random_1 = random_1.uniform(shape=(3, 2), minval=0,maxval=1)
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.3581475 , 0.11322761],
       [0.56670904, 0.6712369 ],
       [0.32565057, 0.17095459]], dtype=float32)>

In [11]:
tf.random.shuffle(random_1, seed=1234)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.32565057, 0.17095459],
       [0.3581475 , 0.11322761],
       [0.56670904, 0.6712369 ]], dtype=float32)>